### ISSUE TITLE
Cannot install IJulia on mit athena

### ISSUE THREAD

**Issue by mjlong** [stevengj/julia-mit#10]
I followed the instructions on this page to install ijulia on athena:
http://ist.mit.edu/node/1403#Julia

But it ended up with the errors below reporting ipython version too low. Is 1.2.1 the single version on athena? 

julia> Pkg.add("IJulia")
INFO: Cloning cache of IJulia from git://github.com/JuliaLang/IJulia.jl.git
INFO: Cloning cache of Nettle from git://github.com/staticfloat/Nettle.jl.git
INFO: Cloning cache of ZMQ from git://github.com/JuliaLang/ZMQ.jl.git
INFO: Installing IJulia v1.0.4
INFO: Installing Nettle v0.1.10
INFO: Installing ZMQ v0.3.0
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
=============================================================================================[ ERROR: IJulia ]==============================================================================================

Jupyter or IPython 3.0 or later is required for IJulia, got IPython 1.2.1 instead
while loading /afs/athena.mit.edu/user/j/l/jlmiao/.julia/v0.3/IJulia/deps/build.jl, in expression starting on line 18

============================================================================================================================================================================================================

==============================================================================================[ BUILD ERRORS ]==============================================================================================

WARNING: IJulia had build errors.

 - packages with build errors remain installed in /afs/athena.mit.edu/user/j/l/jlmiao/.julia/v0.3
 - build the package(s) and all dependencies with `Pkg.build("IJulia")`
 - build a single package by running its `deps/build.jl` script

============================================================================================================================================================================================================
INFO: Package database updated

**Comment by stevengj** [comment]
You should file an Athena ticket if you want them to install a newer version of IPython somewhere.

However, you should try again with the latest IJulia version (`Pkg.update()`), as it should now install its own version of IPython if the one it finds on the system is too old.

**Comment by mjlong** [comment]
Thanks! Another Pkg.update() works!
